note/note/urls.py
from django.contrib import admin
from django.contrib.auth.forms import UserCreationForm
from django.urls import include, path, reverse_lazy
from django.views.generic.edit import CreateView

urlpatterns = [
    path('', include('notes.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path(
        'auth/registration/',
        CreateView.as_view(
            template_name='registration/registration_form.html',
            form_class=UserCreationForm,
            success_url=reverse_lazy('notes:home'),
        ),
        name='registration',
    ),
    path('admin/', admin.site.urls),

]

note/notes/urls.py
from django.urls import path

from . import views

app_name = 'notes'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('rules/', views.RulesView.as_view(), name='rules'),
    path('about/', views.AboutView.as_view(), name='about'),
    path('create/', views.NoteCreateView.as_view(), name='create'),
    path('note/<int:pk>/', views.NoteDetailView.as_view(),
         name='detail'),
    path('list/', views.NoteListView.as_view(), name='list'),
    path('note/<int:pk>/edit/', views.NoteUpdateView.as_view(), name='edit'),
    path('note/<int:pk>/delete/',
         views.NoteDeleteView.as_view(), name='delete'),
    path('profile/<username>/', views.ProfileView.as_view(), name='profile'),

]

note/notes/models.py
from django.contrib.auth import get_user_model
from django.db import models

# Create your models here.

User = get_user_model()


class Note(models.Model):
    title = models.CharField('Заголовок', max_length=69)
    text = models.TextField('Текст', max_length=1000)
    date = models.DateTimeField('Дата', auto_now_add=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, null=True,
                               verbose_name='Автор')

note/notes/forms.py
from django import forms

from .models import Note


class NoteForm(forms.ModelForm):

    class Meta:
        model = Note
        fields = ('title', 'text')

note/notes/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import redirect
from django.urls import reverse, reverse_lazy
from django.views.generic import (CreateView, DeleteView, DetailView, ListView,
                                  TemplateView, UpdateView)

from .forms import NoteForm
from .models import Note, User


class HomeView(TemplateView):
    template_name = 'notes/home.html'


class AboutView(TemplateView):
    template_name = 'notes/about.html'


class RulesView(TemplateView):
    template_name = 'notes/rules.html'


class BaseView(LoginRequiredMixin):
    model = Note

    def get_queryset(self):
        return self.model.objects.filter(author=self.request.user)


class NoteCreateView(BaseView, CreateView):
    form_class = NoteForm
    template_name = 'notes/create.html'

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('notes:list')


class NoteDetailView(BaseView, DetailView):
    template_name = 'notes/detail.html'


class NoteListView(BaseView, ListView):
    template_name = 'notes/list.html'


class NoteUpdateView(BaseView, UpdateView):
    form_class = NoteForm
    template_name = 'notes/create.html'

    def get_success_url(self):
        return reverse_lazy('notes:detail', args=(self.kwargs['pk'],))


class NoteDeleteView(BaseView, DeleteView):
    template_name = 'notes/create.html'
    success_url = reverse_lazy('notes:list')


class ProfileView(LoginRequiredMixin, TemplateView):
    model = User
    template_name = 'notes/profile.html'

    def get_queryset(self):
        return User.objects.filter(username=self.kwargs['username'])

    def dispatch(self, request, *args, **kwargs):
        auth = request.user.is_authenticated
        if request.user.username != kwargs['username'] and auth:
            return redirect('notes:home')
        return super().dispatch(request, *args, **kwargs)

note/templates/base.html
{% load static %} 
{% load django_bootstrap5 %} 
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.2/font/bootstrap-icons.css" integrity="sha384-b6lVK+yci+bfDmaY1u0zE8YYJt0TZxLEAFyYSLHId4xoVvsrQu3INevFKo+Xir8e" crossorigin="anonymous">
  <title>{% block title %}{% endblock %}</title>
  {% bootstrap_css %} 
</head>
<body>
  {% include 'includes/header.html' %}
  <main>
    {% block content %}{% endblock %}
  </main>
</body>
</html>

note/templates/includes/header.html
<header> 

  <nav class="navbar navbar-light" style="background-color: lightskyblue"> 

    <div class="container"> 
      <a class="navbar-brand" href="{% url 'notes:home' %}"><i class="bi bi-card-checklist"></i>Заметки</a> 

      {% with request.resolver_match.view_name as view_name %} 

        <ul class="nav  nav-pills"> 

          <li class="nav-item"> 

            <a class="nav-link {% if view_name == 'notes:about' %} text-white {% endif %}" href="{% url 'notes:about' %}"> 

              О проекте 

            </a> 

          </li> 

          <li class="nav-item"> 

            <a class="nav-link  {% if view_name == 'notes:rules' %} text-white {% endif %}" href="{% url 'notes:rules' %}"> 

              Правила 

            </a> 

          </li> 

          {% if user.is_authenticated %} 

            <div class="btn-group" role="group" aria-label="Basic outlined example"> 

              <button type="button" class="btn btn-outline-primary"><a class="text-decoration-none text-reset  {% if view_name == 'notes:createzzz' %} text-white {% endif %}" 

                  href="{% url 'notes:create' %}">Создать заметку</a></button> 
                  <button type="button" class="btn btn-outline-primary"><a class="text-decoration-none text-reset" 

                    href="{% url 'notes:list' %}">Список заметок</a></button> 

              <button type="button" class="btn btn-outline-primary"><a class="text-decoration-none text-reset" 

                  href="{% url 'notes:profile' user.username %}">{{ user.username }}</a></button> 

              <button type="button" class="btn btn-outline-primary"><a class="text-decoration-none text-reset" 

                  href="{% url 'logout' %}">Выйти</a></button> 

            </div> 

          {% else %} 

            <div class="btn-group" role="group" aria-label="Basic outlined example"> 

              <button type="button" class="btn btn-outline-primary"><a class="text-decoration-none text-reset" 

                  href="{% url 'login' %}">Войти</a></button> 

              <button type="button" class="btn btn-outline-primary"><a class="text-decoration-none text-reset" 

                  href="{% url 'registration' %}">Регистрация</a></button> 

            </div> 

          {% endif %} 

        </ul> 

      {% endwith %} 

    </div> 

  </nav> 

</header> 

note/templates/notes/about.html
{% extends 'base.html' %}
{% block title %}О проекте{% endblock %}
{% block content %}
<h2 class="mb-5 text-center ">Создатель - владелец репозитория <strong>Cardebul</strong></h2>
{% endblock %}

note/templates/notes/create.html
{% extends "base.html" %}
{% load django_bootstrap5 %}
{% block title %}
  {% if '/edit/' in request.path %}
    Редактирование заметки
  {% elif "/delete/" in request.path %}
    Удаление заметки
  {% else %}
    Создание заметки
  {% endif %}
{% endblock %}
{% block content %}
  <div class="col d-flex justify-content-center">
    <div class="card" style="width: 40rem;">
      <div class="card-header">
        {% if '/edit/' in request.path %}
        Редактирование заметки
      {% elif "/delete/" in request.path %}
        Удаление заметки
      {% else %}
        Создание заметки
      {% endif %}
      </div>
      <div class="card-body">
        <form method="post" enctype="multipart/form-data">
          {% csrf_token %}
          {% if not '/delete/' in request.path %}
            {% bootstrap_form form %}
          {% bootstrap_button button_type="submit" content="Отправить" %}

          {% else %}
            <article>
              <h3>Заголовок : {{ note.title }}</h3>
              <p>Текст : {{ note.text|linebreaksbr }}</p>
            </article>
            <a href="{% url 'notes:delete' note.id %}"><button type="button" class="btn btn-danger">Удалить</button></a>
          {% endif %}
        </form>
      </div>
    </div>
  </div>
{% endblock %}

note/templates/notes/detail.html
{% extends "base.html" %}
{% load django_bootstrap5 %}
{% block title %}Заметка {{ note.id }}{% endblock %}
{% block content %}
<div class="col d-flex justify-content-center">
    <div class="card" style="width: 40rem;">
      <div class="card-header">
        <p><a href="{% url 'notes:list' %}">&larr;  К списку заметок</a></p>Заметка с айди {{ note.id }}
      </div>
      <div class="card-body">
<article>
    <h3>Заголовок : {{ note.title }}</h3>
    <p>Текст : {{ note.text|linebreaksbr }}</p>
  </article>
  <hr>
  <p>
    <a href="{% url 'notes:edit' note.id %}"><button type="button" class="btn btn-primary">Редактировать</button></a> 
    
  </p>
  <p>
    <a href="{% url 'notes:delete' note.id %}"><button type="button" class="btn btn-danger">Удалить</button></a>
    
  </p>
      </div>
    </div>
  </div>
{% endblock %}

note/templates/notes/home.html
{% extends 'base.html' %}
{% block title %}Главная{% endblock %}
{% block content %}<h3 class="mb-5 text-center ">На этом сайте вы можете создавать и просматривать свои заметки.</h3>{% endblock %}

note/templates/notes/list.html
{% extends "base.html" %}
{% block content %}
<div class="col d-flex justify-content-center">
    <h2>Список заметок</h2>
    </div>
    <div class="col d-flex justify-content-center">
            <ol class="list-group list-group-numbered">
              {% for note in object_list %}
              <li class="list-group-item"><a href="{% url 'notes:detail' note.id %}"> {{ note.title }}</a></li>
              {% endfor %}
            </ul>
    </div>
    
{% endblock content %}

note/templates/notes/profile.html
{% extends "base.html" %}
{% block title %}
  Страница пользователя {{ instance.username }}
{% endblock %}
{% block content %}
  <h1 class="mb-5 text-center ">Страница пользователя {{ user.username }}</h1>
      {% if user.is_authenticated and request.user == user %}
      <h2  class="mb-5 text-center "><a class="mb-5 text-center " href="{% url 'password_change' %}">Изменить пароль</a></h2>
      {% endif %}

{% endblock %}

note/templates/notes/rules.html
{% extends 'base.html' %}
{% block title %}Правила{% endblock %}
{% block content %}

<ul class="list-group" >
    <li class="list-group-item active" >Правила</li>
    <li class="list-group-item">Вы не вправе просматривать или изменять заметки других пользователей.</li>
    <li class="list-group-item">Надо авторизоваться, чтобы иметь возможность создать заметку.</li>
  </ul>
{% endblock %}